# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

  DeployToDev:
     runs-on: windows-latest
     needs: build
     environment: Dev
     steps:
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
           name: ArtifactName
           path: ${{ github.workplace }}/*
  DeployToUAT:
     runs-on: windows-latest
     needs: DeployToDev
     environment: UAT
     steps:
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
           name: ArtifactName
           path: ${{ github.workplace }}/*        
