# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run Java file
      run: java Add.java
    - name: Print 
      run: echo "Java file ran successfully"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
           name: ArtifactName
           path: ${{ github.workspace }}/*  
  DeployToDev:
     runs-on: windows-latest
     needs: build
     environment: Dev
     steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
           name: ArtifactNameDownloaded

  DeployToUAT:
     runs-on: windows-latest
     needs: DeployToDev
     environment: UAT
     steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
           name: ArtifactNameDownloadUAT
