name: Passing Values

on:
 push:
  branches: [main]

jobs:
 Get-color-input-and-pass-to-nextstep:
   runs-on: ubuntu-latest
   steps:
    - name: set color
      id: color-selector
      run: echo "SELECTED_COLOR=Green" >> $GITHUB_OUTPUT
    - name: Print color in output
      run: echo "The select color is ${{ steps.color-selector.outputs.SELECTED_COLOR }}" >> $GITHUB_STEP_SUMMARY
    - name: Upload Artifacts
      uses: actions/upload-artifacts@v4
      with:
       path: ${{ github.workspace }}/*
     
      
      
