name: First Workflow

on: 
 push:
   branches: [main]

jobs:
  First Workflow:
   runs-on: ubuntu-latest

   steps:
   -uses: actions/checkout@v4
   -name: Setup JDK
    -uses: actions/setup-java@v2
     with:
      java-version: '17'
      distribution: 'temurin'
   -name: Run the File
     run: java Add.java
